// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3_hhl-I0xxZS1LkNXFp2pIUe9P5xI00',
    appId: '1:782971507537:web:4c208e00ecd8f28cca3970',
    messagingSenderId: '782971507537',
    projectId: 'recipe-share-app-fcf53',
    authDomain: 'recipe-share-app-fcf53.firebaseapp.com',
    storageBucket: 'recipe-share-app-fcf53.firebasestorage.app',
    measurementId: 'G-E65TLB5QM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7aY7RwV3bopkZQiNAZbvrOYVKuAG_rLY',
    appId: '1:782971507537:android:9ce3ff52c175387cca3970',
    messagingSenderId: '782971507537',
    projectId: 'recipe-share-app-fcf53',
    storageBucket: 'recipe-share-app-fcf53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeP4cChXXxBamHRQILG4kfK9jZtH3KBco',
    appId: '1:782971507537:ios:d0dacb7080cde0a7ca3970',
    messagingSenderId: '782971507537',
    projectId: 'recipe-share-app-fcf53',
    storageBucket: 'recipe-share-app-fcf53.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeP4cChXXxBamHRQILG4kfK9jZtH3KBco',
    appId: '1:782971507537:ios:d0dacb7080cde0a7ca3970',
    messagingSenderId: '782971507537',
    projectId: 'recipe-share-app-fcf53',
    storageBucket: 'recipe-share-app-fcf53.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW3_hhl-I0xxZS1LkNXFp2pIUe9P5xI00',
    appId: '1:782971507537:web:ba32f8383142c65eca3970',
    messagingSenderId: '782971507537',
    projectId: 'recipe-share-app-fcf53',
    authDomain: 'recipe-share-app-fcf53.firebaseapp.com',
    storageBucket: 'recipe-share-app-fcf53.firebasestorage.app',
    measurementId: 'G-D0ZXBRW2C3',
  );
}
